apiVersion: v1
kind: Pod
metadata:
  labels:
    run: testpod
  name: hexapod
spec:
  containers:
  - image: nginx
    name: testpod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst

